#!/usr/bin/env bash

## Variáveis
source .env

## Define usuário e Permissões dos arquivos
chown $WWWUSER:www-data -R /var/www/html/meugrupovip

chmod 775 -R /var/www/html/meugrupovip

### Instala os pacotes do composer
composer install --no-interaction --no-dev

### Otimização da aplicação
php artisan clear-compiled && php artisan optimize:clear

## GIT
git config --system --add safe.directory /var/www/html/meugrupovip
git config --system user.name "$GITNAME"
git config --system user.email "$GITEMAIL"

exec /usr/sbin/apache2ctl -D FOREGROUND